// apps/docs/src/components/ui/scroll-area.tsx
import { cn } from '@/lib/utils'
import { ScrollArea as ScrollAreaPrimitive } from 'radix-ui'
import * as React from 'react'

type ScrollAreaProps = React.ComponentProps<typeof ScrollAreaPrimitive.Root> & {
  fades?: boolean
  viewportClassName?: string
}

type ScrollAreaFadeState = {
  top: boolean
  bottom: boolean
}

function ScrollArea({
  className,
  fades = false,
  viewportClassName,
  children,
  type = 'scroll',
  ...props
}: ScrollAreaProps) {
  const viewportRef = React.useRef<React.ComponentRef<typeof ScrollAreaPrimitive.Viewport>>(null)
  const [fadeState, setFadeState] = React.useState<ScrollAreaFadeState>({
    top: false,
    bottom: false,
  })

  const updateFadeState = React.useCallback(() => {
    const viewport = viewportRef.current
    if (!viewport || !fades) return

    const maxScrollTop = viewport.scrollHeight - viewport.clientHeight
    const next = {
      top: maxScrollTop > 1 && viewport.scrollTop > 1,
      bottom: maxScrollTop > 1 && viewport.scrollTop < maxScrollTop - 1,
    }

    setFadeState(current =>
      current.top === next.top && current.bottom === next.bottom ? current : next
    )
  }, [fades])

  React.useEffect(() => {
    if (!fades) return

    const viewport = viewportRef.current
    if (!viewport) return

    updateFadeState()
    viewport.addEventListener('scroll', updateFadeState, { passive: true })

    const observer = new ResizeObserver(updateFadeState)
    observer.observe(viewport)
    if (viewport.firstElementChild) observer.observe(viewport.firstElementChild)

    return () => {
      viewport.removeEventListener('scroll', updateFadeState)
      observer.disconnect()
    }
  }, [fades, updateFadeState])

  return (
    <ScrollAreaPrimitive.Root
      data-slot="scroll-area"
      type={type}
      scrollHideDelay={250}
      className={cn('relative', className)}
      {...props}
    >
      <ScrollAreaPrimitive.Viewport
        ref={viewportRef}
        data-slot="scroll-area-viewport"
        className={cn(
          'ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 size-full rounded-[inherit] transition-[color,box-shadow] focus-visible:ring-4 focus-visible:outline-1',
          viewportClassName
        )}
      >
        {children}
      </ScrollAreaPrimitive.Viewport>
      {fades && (
        <>
          <div
            aria-hidden="true"
            data-slot="scroll-area-fade-top"
            className={cn(
              'from-background pointer-events-none absolute inset-x-0 top-0 z-10 h-8 bg-gradient-to-b to-transparent transition-opacity',
              fadeState.top ? 'opacity-100' : 'opacity-0'
            )}
          />
          <div
            aria-hidden="true"
            data-slot="scroll-area-fade-bottom"
            className={cn(
              'from-background pointer-events-none absolute inset-x-0 bottom-0 z-10 h-8 bg-gradient-to-t to-transparent transition-opacity',
              fadeState.bottom ? 'opacity-100' : 'opacity-0'
            )}
          />
        </>
      )}
      <ScrollBar />
      <ScrollAreaPrimitive.Corner />
    </ScrollAreaPrimitive.Root>
  )
}

function ScrollBar({
  className,
  orientation = 'vertical',
  ...props
}: React.ComponentProps<typeof ScrollAreaPrimitive.ScrollAreaScrollbar>) {
  return (
    <ScrollAreaPrimitive.ScrollAreaScrollbar
      data-slot="scroll-area-scrollbar"
      orientation={orientation}
      className={cn(
        'flex touch-none p-px transition-colors select-none',
        orientation === 'vertical' && 'h-full w-2.5 border-l border-l-transparent',
        orientation === 'horizontal' && 'h-2.5 flex-col border-t border-t-transparent',
        className
      )}
      {...props}
    >
      <ScrollAreaPrimitive.ScrollAreaThumb
        data-slot="scroll-area-thumb"
        className="bg-border relative flex-1 rounded-full"
      />
    </ScrollAreaPrimitive.ScrollAreaScrollbar>
  )
}

export { ScrollArea, ScrollBar }

// apps/web/src/lib/components/ui/scroll-area/scroll-area.svelte
<script lang="ts">
  import { cn, type WithoutChild } from '$lib/utils'
  import { ScrollArea as ScrollAreaPrimitive } from 'bits-ui'
  import { Scrollbar } from './index.js'

  let {
    ref = $bindable(null),
    viewportRef = $bindable(null),
    class: className,
    orientation = 'vertical',
    scrollbarXClasses = '',
    scrollbarYClasses = '',
    fadeSize = 24,
    fadeColor = 'background-l0',
    children,
    ...restProps
  }: WithoutChild<ScrollAreaPrimitive.RootProps> & {
    orientation?: 'vertical' | 'horizontal' | 'both' | undefined
    scrollbarXClasses?: string | undefined
    scrollbarYClasses?: string | undefined
    viewportRef?: HTMLElement | null
    fadeSize?: number
    fadeColor?: string
  } = $props()

  let internalViewportRef = $state<HTMLElement | null>(null)
  let showTopFade = $state(false)
  let showBottomFade = $state(false)

  function updateFades() {
    const viewport = internalViewportRef
    if (!viewport) return

    const { scrollTop, scrollHeight, clientHeight } = viewport
    const threshold = 10

    showTopFade = scrollTop > threshold
    showBottomFade = scrollTop + clientHeight < scrollHeight - threshold
  }

  $effect(() => {
    const viewport = internalViewportRef
    if (!viewport) return

    updateFades()

    viewport.addEventListener('scroll', updateFades, { passive: true })
    const resizeObserver = new ResizeObserver(updateFades)
    resizeObserver.observe(viewport)

    return () => {
      viewport.removeEventListener('scroll', updateFades)
      resizeObserver.disconnect()
    }
  })

  $effect(() => {
    viewportRef = internalViewportRef
  })

  const topFadeStyle = $derived(
    `height: ${fadeSize}px; background: linear-gradient(to bottom, var(--${fadeColor}), transparent);`
  )
  const bottomFadeStyle = $derived(
    `height: ${fadeSize}px; background: linear-gradient(to top, var(--${fadeColor}), transparent);`
  )
</script>

<ScrollAreaPrimitive.Root
  bind:ref
  data-slot="scroll-area"
  class={cn('relative', className)}
  {...restProps}
>
  <ScrollAreaPrimitive.Viewport
    bind:ref={internalViewportRef}
    data-slot="scroll-area-viewport"
    class="ring-ring/10 dark:ring-ring/20 dark:outline-ring/40 outline-ring/50 size-full rounded-[inherit] focus-visible:outline-1 focus-visible:ring-4"
  >
    {@render children?.()}
  </ScrollAreaPrimitive.Viewport>

  <div
    class={cn(
      'pointer-events-none absolute inset-x-0 top-0',
      showTopFade ? 'opacity-100' : 'opacity-0'
    )}
    style={topFadeStyle}
    aria-hidden="true"
  ></div>

  <div
    class={cn(
      'pointer-events-none absolute inset-x-0 bottom-0',
      showBottomFade ? 'opacity-100' : 'opacity-0'
    )}
    style={bottomFadeStyle}
    aria-hidden="true"
  ></div>

  {#if orientation === 'vertical' || orientation === 'both'}
    <Scrollbar orientation="vertical" class={scrollbarYClasses} />
  {/if}
  {#if orientation === 'horizontal' || orientation === 'both'}
    <Scrollbar orientation="horizontal" class={scrollbarXClasses} />
  {/if}
  <ScrollAreaPrimitive.Corner />
</ScrollAreaPrimitive.Root>
